name: C/C++ CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pdflatex
      run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra
    - name: Build pdf
      run: make hcmus
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: build/hcmus.pdf
    - name: Run compiles
      run: make test-compiles
    - name: Run stress tests
      run: make test
